### ISSUE TITLE
Any tips for large datasets?

### ISSUE THREAD

**Issue by deweydb** [fillipe-gsm/python-tsp#31]
I tried to run this with 41,000 data points and my computer ran out of ram and crashed. Is there any advice you can share on how to run this with bigger datasets?

**Comment by deweydb** [comment]
Thank you very much this was extremely helpful and I greatly appreciate that time and effort you put into sharing all this information with me.

**Comment by fillipe-gsm** [comment]
Since there is no action item to be performed here, I will close this issue.
