### ISSUE TITLE
Can't import a couple of functions.

### ISSUE THREAD

**Issue by pepeto** [fillipe-gsm/python-tsp#48]
After pip installed the library, I was trying all the functions in order to process a distance matrix but when I tried to import a couple of them (the commented # ones), an error appeared:

ImportError: cannot import name 'solve_tsp_lin_kernighan' from 'python_tsp.heuristics' (M:\Working\- ENVS\python3.9\lib\site-packages\python_tsp\heuristics\__init__.py)

```
from python_tsp.exact import solve_tsp_brute_force
from python_tsp.exact import solve_tsp_branch_and_bound
from python_tsp.exact import solve_tsp_dynamic_programming

from python_tsp.heuristics import solve_tsp_local_search 
#from python_tsp.heuristics import solve_tsp_lin_kernighan                                   
#from python_tsp.heuristics import solve_tsp_record_to_record
from python_tsp.heuristics import solve_tsp_simulated_annealing
```

**Comment by fillipe-gsm** [comment]
Sorry, this was my mistake.

These two methods were added right after my last publish to PyPI and they got left out...

I republished version 0.4.1 fixing that, can you update it and try again?

Two relevant points:
- As explained in the README, I am keeping Python compatibility with Debian stable, so this version supports Python 3.9+ (apparently not a problem given your traceback);
- Just keep in mind that these are new heuristics and aren't as tested as the existing ones, so if you experience any problems feel free to open another issue.

**Comment by fillipe-gsm** [comment]
I think this problem got solved, right?

I am going to close this issue.
Feel free to open a new one if you find another problem.
