### ISSUE TITLE
Numpy 2.0 support

### ISSUE THREAD

**Issue by CoolCat467** [fillipe-gsm/python-tsp#58]
Trying to use this project as a dependency, having numpy as a dependency myself I get an error that this project does not support numpy 2.0.0.
I would be happy to help with that, but thought I'd make an issue first.

**Comment by fillipe-gsm** [comment]
Hey, @CoolCat467, sorry for the late reply, but thanks for the effort on updating Numpy!

Despite all tests passing and the project not relying too heavily on Numpy, it is still a major change on a dependency. So, for safety, I would like to publish this to a semi-major 0.5.0.

This means that if you have `python-tsp` as dependency you would probably need to manually update it to `0.5.0` in your `requirements.txt` or `pyproject.toml` files (at least `poetry` I believe would not update it automatically with a `poetry update`).

If you're okay with this, I'll publish the new version.

**Comment by CoolCat467** [comment]
Yea sure thing, 0.5.0 makes sense, numpy major release is definitely a higher version bump.

**Comment by fillipe-gsm** [comment]
Great, I uploaded the library to version 0.5.0 and updated the README accordingly.

Thank you for the contribution!

**Comment by fillipe-gsm** [comment]
Hey, @AlexDuchnowski, I'll take a look if it is possible to allow numpy < 2.0.0 and >= 2.0.0 to co-exist.
In the meanwhile, you most likely can install version 0.4.2 instead:

```sh
pip install python-tsp==0.4.2
```

The only difference is the numpy version, so you would get the same features but this version is compatible with numpy <= 2.0.0.

**Comment by AlexDuchnowski** [comment]
@fillipe-gsm Sweet, thanks! (Also, thanks for the super quick response! I feel guilty for taking this long to respond after you answered my question almost instantly.)
@CoolCat467 Good point. I looked into it, and it seems I just had a few packages I hadn't updated in a little while, and so I can actually upgrade to numpy 2. Even so, I think it would be good to allow for backward compatibility if this package can still be used with earlier numpy versions. Anyway, thanks for encouraging me to check!
